<!-- header -->
<header class="header">
  <div class="header__inner">
    <div class="header__logo">
      <a href="https://www.fujisash.co.jp/" target="_blank">
        <img src="{{HOME}}assets/img/logo.svg" alt="ロゴ画像">
      </a>
    </div>
    <div class="nav__toggle">
      <div>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
    <nav class="gloval__nav">
      <ul class="header__list">
        <li class="header__item">
          <a href="{{HOME}}">キャンペーンTOP</a>
        </li>
        <!--
        <li class="header__item orenge">
          <a href="#">補助事業</a>
          <ul class="dropdown__lists">
            <li class="dropdown__list">
              <a href="{{HOME}}kodomo/">子育てグリーン住宅支援事業</a>
            </li>
            <li class="dropdown__list">
              <a href="{{HOME}}mado/">先進的窓リノベ2024事業</a>
            </li>
            <li class="dropdown__list">
              <a href="https://kyutou-shoene2024.meti.go.jp" target="_blank">給湯省エネ2024事業</a>
            </li>
            <li class="dropdown__list">
              <a href="https://chintai-shoene2024.meti.go.jp" target="_blank">賃貸集合給湯省エネ2024事業</a>
            </li>
          </ul>
        </li>
        -->
        <li class="header__item">
          <a href="https://jutaku-shoene2025.mlit.go.jp/" target="_blank">キャンペーン事業HPへ</a>
        </li>
        <li class="header__btn">
          <a class="header__link" href="{{HOME}}files/products.pdf" target="_blank">不二サッシ対象製品一覧表</a>
        </li>
      </ul>
    </nav>
  </div>
</header>